name: ec2 terraform destroy

on:
  workflow_dispatch:
    inputs: 
      CONFIRM_DESTROY:
        description: "Type 'destroy' to confirm deletion"
        required: true

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform-destroy:
    name: terraform destroy
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./ec2/terraform/environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.CONFIRM_DESTROY }}" != "destroy" ]; then
            echo "Error: You must type 'destroy' to confirm deletion"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.5.0"

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform variables
        run: |
          echo "TF_VAR_instance_name=${{ vars.INSTANCE_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_ami_id=${{ vars.AMI_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_instance_type=${{ vars.INSTANCE_TYPE }}" >> $GITHUB_ENV
          echo "TF_VAR_vpc_id=${{ secrets.VPC_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_subnet_id=${{ secrets.SUBNET_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_key_name=${{ secrets.KEY_NAME }}" >> $GITHUB_ENV
          
      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve
